services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - migrate

  migrate:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app    

volumes:
  db_data:
